# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addresources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Resource', models.CharField(max_length=500)),
                ('HS_Code', models.IntegerField()),
                ('Name_of_Matching_Resource', models.CharField(max_length=500)),
                ('Matching_HS_Code', models.IntegerField()),
            ],
        ),
    ]
