# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresources',
            name='hi',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
