# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0002_addresources_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresources',
            name='hi',
        ),
        migrations.AddField(
            model_name='addresources',
            name='Check_if_matches_interchangeable',
            field=models.BooleanField(default=True),
        ),
    ]
