# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0003_auto_20170117_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmatchingresources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Matching_Resource', models.CharField(max_length=500)),
                ('Matching_HS_Code', models.IntegerField()),
                ('Check_if_matches_interchangeable', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='addresources',
            name='Check_if_matches_interchangeable',
        ),
        migrations.RemoveField(
            model_name='addresources',
            name='Matching_HS_Code',
        ),
        migrations.RemoveField(
            model_name='addresources',
            name='Name_of_Matching_Resource',
        ),
        migrations.AddField(
            model_name='addmatchingresources',
            name='addresources',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresources.addresources'),
        ),
    ]
