# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0004_auto_20170118_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='editresources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Resource', models.CharField(max_length=500)),
                ('HS_Code', models.IntegerField()),
            ],
        ),
    ]
