# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0005_editresources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmatchingresources',
            old_name='addresources',
            new_name='add_resources',
        ),
    ]
