# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0008_auto_20170215_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmatchingresources',
            name='Extraction',
            field=models.IntegerField(default=0),
        ),
    ]
