# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0009_addmatchingresources_extraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmatchingresources',
            old_name='Extraction',
            new_name='Extraction_rate',
        ),
    ]
