# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0012_auto_20170630_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmatchingresources',
            name='Extraction_rate',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='addmatchingresources',
            name='Source',
            field=models.CharField(max_length=500),
        ),
    ]
