# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresources', '0014_addmatchingresources_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmatchingresources',
            name='Catalyst',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addmatchingresources',
            name='Temperature',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addmatchingresources',
            name='Method',
            field=models.CharField(help_text='Enter field documentation', max_length=500),
        ),
    ]
