# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=99999, unique=True)),
                ('hs_code', models.CharField(max_length=99999, unique=True)),
                ('description', models.CharField(max_length=99999, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
